print("HUBNE")
print("1. Apply for examination :")
print("2. Apply for result :")
print("3. Contact us..")
ch=int(input("Please enter your choice option :"))
if ch==1:
    name=input("Please Enter your Name :")
    ph=int(input("Please Enter your contact number :"))
    sch=input("Please Enter you schoool/collage name :")
    print("Thanks you. we will send your id no. on your contact number")
if ch==2:
    id=int(input("Please Enter your id no :"))
    name2=input("Enter your Name :")
    ph2=input("Please enter your phone number :")
    em=input("Please Enter your Email address :")
    print("Your submitted form is sucessfully submited")
    print("Thanks you we will send your result as soon as poosible on your given E-mail address.")
if ch==3:
    print("HUBNET")
    print("For any query you can contact me mail me on given adress and contact no.")
    print("Contact number :09334179627")
    print("Email-INFO@HUBNETTECH.NET")
    print("Website-www.hubnet.org")
    print("Address - 2nd Floor, JJ Complex, E Boring Canal Rd, Opposite of Bharat Petrolium ,Patna, Bihar 800001")
    print("Thanks your for visiting us.")